import { ConflictException, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { BookingStatus } from "../generated/prisma/enums.js";
import { BookingsService } from "./bookings.service.js";
describe("BookingsService", () => {
  let tx: any; let service: BookingsService;
  beforeEach(() => { tx = { booking: { findMany: vi.fn(), count: vi.fn(), findFirst: vi.fn(), create: vi.fn(), updateMany: vi.fn(), findFirstOrThrow: vi.fn() }, availabilityBlock: { findFirst: vi.fn().mockResolvedValue(null) }, customer: { findFirst: vi.fn() }, service: { findFirst: vi.fn() }, location: { findFirst: vi.fn() }, bookingStatusHistory: { create: vi.fn() }, auditEvent: { create: vi.fn() } }; service = new BookingsService({ withTenant: vi.fn((_id, fn) => fn(tx)) } as never); });
  it("paginates only the tenant's bookings", async () => { tx.booking.findMany.mockResolvedValue([]); tx.booking.count.mockResolvedValue(0); await expect(service.list("t", { page: 2, limit: 10 })).resolves.toEqual({ items: [], page: 2, limit: 10, total: 0 }); expect(tx.booking.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ tenantId: "t" }), skip: 10, take: 10 })); });
  it("does not disclose cross-tenant bookings", async () => { tx.booking.findFirst.mockResolvedValue(null); await expect(service.get("t", "b")).rejects.toBeInstanceOf(NotFoundException); });
  it("creates immutable service snapshots and history in one transaction", async () => {
    tx.customer.findFirst.mockResolvedValue({ id: "c" }); tx.service.findFirst.mockResolvedValue({ id: "s", durationMinutes: 30, name: "Cut", price: null, currency: "CRC" }); tx.location.findFirst.mockResolvedValue({ id: "l", timezone: "UTC", tenant: { timezone: "UTC" }, businessHours: [{ dayOfWeek: new Date(Date.now() + 3600000).getUTCDay(), isClosed: false, openTime: new Date("1970-01-01T00:00:00Z"), closeTime: new Date("1970-01-01T23:59:00Z") }] }); tx.booking.findFirst.mockResolvedValue(null); tx.booking.create.mockResolvedValue({ id: "b" });
    await service.create("t", "u", { customerId: "c", serviceId: "s", locationId: "l", startAt: new Date(Date.now() + 3600000).toISOString() });
    expect(tx.booking.create).toHaveBeenCalledWith({ data: expect.objectContaining({ tenantId: "t", serviceName: "Cut", serviceDurationMinutes: 30 }) }); expect(tx.bookingStatusHistory.create).toHaveBeenCalled(); expect(tx.auditEvent.create).toHaveBeenCalled();
  });
  it("rejects unavailable references", async () => { tx.customer.findFirst.mockResolvedValue(null); tx.service.findFirst.mockResolvedValue(null); tx.location.findFirst.mockResolvedValue(null); await expect(service.create("t", "u", { customerId: "c", serviceId: "s", locationId: "l", startAt: new Date(Date.now() + 10000).toISOString() })).rejects.toBeInstanceOf(UnprocessableEntityException); });
  it("rejects overlapping active bookings", async () => { tx.customer.findFirst.mockResolvedValue({ id: "c" }); tx.service.findFirst.mockResolvedValue({ id: "s", durationMinutes: 30 }); tx.location.findFirst.mockResolvedValue({ id: "l", tenant: { timezone: "UTC" }, businessHours: [] }); tx.booking.findFirst.mockResolvedValue({ id: "collision" }); await expect(service.create("t", "u", { customerId: "c", serviceId: "s", locationId: "l", startAt: new Date(Date.now() + 10000).toISOString() })).rejects.toBeInstanceOf(ConflictException); });
  it("rejects availability blocks", async () => { tx.customer.findFirst.mockResolvedValue({ id: "c" }); tx.service.findFirst.mockResolvedValue({ id: "s", durationMinutes: 30 }); tx.location.findFirst.mockResolvedValue({ id: "l", tenant: { timezone: "UTC" }, businessHours: [] }); tx.booking.findFirst.mockResolvedValue(null); tx.availabilityBlock.findFirst.mockResolvedValue({ id: "blocked" }); await expect(service.create("t", "u", { customerId: "c", serviceId: "s", locationId: "l", startAt: new Date(Date.now() + 10000).toISOString() })).rejects.toBeInstanceOf(ConflictException); });
  it("enforces the transition state machine", async () => { tx.booking.findFirst.mockResolvedValue({ status: BookingStatus.COMPLETED }); await expect(service.transition("t", "b", "u", BookingStatus.CONFIRMED, 1)).rejects.toBeInstanceOf(UnprocessableEntityException); });
  it("detects optimistic concurrency conflicts", async () => { tx.booking.findFirst.mockResolvedValue({ status: BookingStatus.PENDING }); tx.booking.updateMany.mockResolvedValue({ count: 0 }); await expect(service.transition("t", "b", "u", BookingStatus.CONFIRMED, 1)).rejects.toBeInstanceOf(ConflictException); });
  it("persists an allowed transition and audit history", async () => { tx.booking.findFirst.mockResolvedValue({ status: BookingStatus.PENDING }); tx.booking.updateMany.mockResolvedValue({ count: 1 }); tx.booking.findFirstOrThrow.mockResolvedValue({ status: BookingStatus.CONFIRMED }); await expect(service.transition("t", "b", "u", BookingStatus.CONFIRMED, 1, "ok")).resolves.toMatchObject({ status: BookingStatus.CONFIRMED }); expect(tx.bookingStatusHistory.create).toHaveBeenCalled(); });
  it("rejects rescheduling missing or terminal bookings", async () => { tx.booking.findFirst.mockResolvedValueOnce(null); await expect(service.reschedule("t", "b", "u", 1, "2030-01-01T10:00:00Z")).rejects.toBeInstanceOf(NotFoundException); tx.booking.findFirst.mockResolvedValueOnce({ status: BookingStatus.CANCELLED }); await expect(service.reschedule("t", "b", "u", 1, "2030-01-01T10:00:00Z")).rejects.toBeInstanceOf(UnprocessableEntityException); });
  it("rejects past reschedules", async () => { tx.booking.findFirst.mockResolvedValue({ status: BookingStatus.CONFIRMED, serviceDurationMinutes: 30 }); await expect(service.reschedule("t", "b", "u", 1, "2020-01-01T10:00:00Z")).rejects.toBeInstanceOf(UnprocessableEntityException); });
  it("reschedules within business hours and records an audit event", async () => { tx.booking.findFirst.mockResolvedValueOnce({ id: "b", status: BookingStatus.CONFIRMED, locationId: "l", serviceDurationMinutes: 30, startAt: new Date("2029-01-01T10:00:00Z") }).mockResolvedValueOnce(null); tx.location.findFirst.mockResolvedValue({ timezone: "UTC", tenant: { timezone: "UTC" }, businessHours: [{ dayOfWeek: 2, isClosed: false, openTime: new Date("1970-01-01T08:00:00Z"), closeTime: new Date("1970-01-01T18:00:00Z") }] }); tx.booking.updateMany.mockResolvedValue({ count: 1 }); tx.booking.findFirstOrThrow.mockResolvedValue({ id: "b", version: 2 }); await expect(service.reschedule("t", "b", "u", 1, "2030-01-01T10:00:00Z")).resolves.toMatchObject({ version: 2 }); expect(tx.auditEvent.create).toHaveBeenCalled(); });
  it("detects concurrent reschedules", async () => { tx.booking.findFirst.mockResolvedValueOnce({ id: "b", status: BookingStatus.CONFIRMED, locationId: "l", serviceDurationMinutes: 30, startAt: new Date("2029-01-01T10:00:00Z") }).mockResolvedValueOnce(null); tx.location.findFirst.mockResolvedValue({ timezone: "UTC", tenant: { timezone: "UTC" }, businessHours: [{ dayOfWeek: 2, isClosed: false, openTime: new Date("1970-01-01T08:00:00Z"), closeTime: new Date("1970-01-01T18:00:00Z") }] }); tx.booking.updateMany.mockResolvedValue({ count: 0 }); await expect(service.reschedule("t", "b", "u", 1, "2030-01-01T10:00:00Z")).rejects.toBeInstanceOf(ConflictException); });
});
