import { ConflictException, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { TrackingService } from "./tracking.service.js";
describe("TrackingService", () => {
  const tenantId = "f9dd70d0-0f7b-497c-9d02-302859f65f1e";
  const token = `${tenantId}.secret-with-at-least-thirty-two-characters`;
  let prisma: any; let service: TrackingService;
  beforeEach(() => { prisma = { booking: { findFirst: vi.fn(), updateMany: vi.fn(), findFirstOrThrow: vi.fn() }, bookingPublicToken: { create: vi.fn(), findUnique: vi.fn(), findFirst: vi.fn() }, bookingStatusHistory: { create: vi.fn() }, auditEvent: { create: vi.fn() }, availabilityBlock: { findFirst: vi.fn() }, location: { findFirst: vi.fn().mockResolvedValue({ timezone: "UTC", tenant: { timezone: "UTC" }, businessHours: [{ dayOfWeek: 2, isClosed: false, openTime: new Date("1970-01-01T08:00:00Z"), closeTime: new Date("1970-01-01T18:00:00Z") }] }) }, withTenant: vi.fn((_tenantId, fn) => fn(prisma)) }; service = new TrackingService(prisma); });
  it("stores only a digest and returns the one-time plaintext token", async () => { prisma.booking.findFirst.mockResolvedValue({ id: "b" }); prisma.bookingPublicToken.create.mockResolvedValue({}); const result = await service.issue(tenantId, "b"); const stored = prisma.bookingPublicToken.create.mock.calls[0][0].data.tokenHash; expect(stored).toMatch(/^[a-f0-9]{64}$/); expect(stored).not.toBe(result.token); expect(result.token.startsWith(`${tenantId}.`)).toBe(true); });
  it("refuses to issue links for another tenant", async () => { prisma.booking.findFirst.mockResolvedValue(null); await expect(service.issue("t", "b")).rejects.toBeInstanceOf(NotFoundException); });
  it("returns the deliberately minimized public projection", async () => { const booking = { id: "b", status: "CONFIRMED" }; prisma.bookingPublicToken.findFirst.mockResolvedValue({ revokedAt: null, expiresAt: new Date(Date.now() + 10000), booking }); await expect(service.get(token)).resolves.toBe(booking); expect(prisma.bookingPublicToken.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ tenantId, tokenHash: expect.stringMatching(/^[a-f0-9]{64}$/) }) })); });
  it("uses the same not-found response for revoked, expired and unknown links", async () => { for (const record of [null, { revokedAt: new Date(), expiresAt: new Date(Date.now() + 10000) }, { revokedAt: null, expiresAt: new Date(0) }]) { prisma.bookingPublicToken.findFirst.mockResolvedValue(record); await expect(service.get(token)).rejects.toBeInstanceOf(NotFoundException); } });
  it("does not reveal unknown public mutation tokens", async () => { prisma.bookingPublicToken.findUnique.mockResolvedValue(null); await expect(service.cancel("secret", 1)).rejects.toBeInstanceOf(NotFoundException); expect(prisma.withTenant).not.toHaveBeenCalled(); });
  it("revalidates token expiry inside the tenant transaction", async () => { prisma.bookingPublicToken.findFirst.mockResolvedValue(null); await expect(service.cancel(token, 1)).rejects.toBeInstanceOf(NotFoundException); expect(prisma.booking.updateMany).not.toHaveBeenCalled(); });
  it("cancels with optimistic concurrency, null actor, history and audit", async () => { prisma.bookingPublicToken.findFirst.mockResolvedValue({ bookingId: "b" }); prisma.booking.findFirst.mockResolvedValue({ id: "b", status: "CONFIRMED" }); prisma.booking.updateMany.mockResolvedValue({ count: 1 }); prisma.booking.findFirstOrThrow.mockResolvedValue({ id: "b", status: "CANCELLED" }); await expect(service.cancel(token, 4, "customer request")).resolves.toMatchObject({ status: "CANCELLED" }); expect(prisma.bookingStatusHistory.create).toHaveBeenCalledWith({ data: expect.objectContaining({ actorId: null, fromStatus: "CONFIRMED", toStatus: "CANCELLED" }) }); expect(prisma.auditEvent.create).toHaveBeenCalledWith({ data: expect.objectContaining({ actorUserId: null }) }); });
  it("rejects terminal public cancellation and concurrent writes", async () => { prisma.bookingPublicToken.findFirst.mockResolvedValue({ bookingId: "b" }); prisma.booking.findFirst.mockResolvedValue({ id: "b", status: "COMPLETED" }); await expect(service.cancel(token, 1)).rejects.toBeInstanceOf(UnprocessableEntityException); prisma.booking.findFirst.mockResolvedValue({ id: "b", status: "PENDING" }); prisma.booking.updateMany.mockResolvedValue({ count: 0 }); await expect(service.cancel(token, 1)).rejects.toBeInstanceOf(ConflictException); });
  it("reschedules publicly after collision and block checks", async () => { prisma.bookingPublicToken.findFirst.mockResolvedValue({ bookingId: "b" }); prisma.booking.findFirst.mockResolvedValueOnce({ id: "b", status: "PENDING", locationId: "l", serviceDurationMinutes: 30, startAt: new Date("2029-01-01T10:00:00Z") }).mockResolvedValueOnce(null); prisma.availabilityBlock.findFirst.mockResolvedValue(null); prisma.booking.updateMany.mockResolvedValue({ count: 1 }); prisma.booking.findFirstOrThrow.mockResolvedValue({ id: "b", version: 2 }); await expect(service.reschedule(token, 1, "2030-01-01T10:00:00Z", "later")).resolves.toMatchObject({ version: 2 }); expect(prisma.auditEvent.create).toHaveBeenCalledWith({ data: expect.objectContaining({ actorUserId: null, action: "booking.public_rescheduled" }) }); });
  it("rejects past, conflicting and blocked reschedules", async () => { prisma.bookingPublicToken.findFirst.mockResolvedValue({ bookingId: "b" }); prisma.booking.findFirst.mockResolvedValue({ id: "b", status: "PENDING", locationId: "l", serviceDurationMinutes: 30, startAt: new Date() }); await expect(service.reschedule(token, 1, "2020-01-01T10:00:00Z")).rejects.toBeInstanceOf(UnprocessableEntityException); prisma.booking.findFirst.mockReset().mockResolvedValueOnce({ id: "b", status: "PENDING", locationId: "l", serviceDurationMinutes: 30, startAt: new Date() }).mockResolvedValueOnce({ id: "other" }); prisma.availabilityBlock.findFirst.mockResolvedValue(null); await expect(service.reschedule(token, 1, "2030-01-01T10:00:00Z")).rejects.toBeInstanceOf(ConflictException); prisma.booking.findFirst.mockReset().mockResolvedValueOnce({ id: "b", status: "PENDING", locationId: "l", serviceDurationMinutes: 30, startAt: new Date() }).mockResolvedValueOnce(null); prisma.availabilityBlock.findFirst.mockResolvedValue({ id: "block" }); await expect(service.reschedule(token, 1, "2030-01-01T10:00:00Z")).rejects.toBeInstanceOf(ConflictException); });
});
